name: "Reusable ci typos workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  types:
    name: ğŸ§ğŸ“ğŸ“
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/mdns-browser-ubuntu-builder:v1@sha256:41b291e0292a111400ede6b3df9dfb0b1547cf685a89a3cf11b94b4ba120b7f1

    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: ğŸ“ Check spelling using typos-action
        uses: crate-ci/typos@07d900b8fa1097806b8adb6391b0d3e0ac2fdea7 # v1.39.0
        with:
          config: ./typos.toml
