name: "CI"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  # measure against bitrot
  # also rotates docker images monthly
  schedule:
    - cron: "0 0 1 * *"

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

concurrency:
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  label-pr:
    if: github.event_name == 'pull_request'
    name: "üè∑Ô∏è Label PR"
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config file
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af # v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  changes:
    name: "üîç Detect Changes"
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.filter.outputs.android }}
      aur: ${{ steps.filter.outputs.aur }}
      branch: ${{ steps.branch.outputs.branch }}
      desktop: ${{ steps.filter.outputs.desktop }}
      docker: ${{ steps.filter.outputs.docker }}
      tauri: ${{ steps.filter.outputs.tauri }}
      tests: ${{ steps.filter.outputs.tests }}
      void: ${{ steps.filter.outputs.void }}
      winget: ${{ steps.filter.outputs.winget }}
    steps:
      - name: üîÑ Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: üîç Check for changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            android:
              - '.github/workflows/android.yml'
              - 'src-tauri/capabilities/mobile.json'
              - 'src-tauri/icons/android/**'
              - 'src-tauri/tauri.android.conf.json'
            aur:
              - aur-template/**
              - '.github/workflows/aur.yml'
              - '.github/actions/lateste-release-info/action.yml'
            desktop:
              - '.github/workflows/desktop.yml'
              - 'src-tauri/capabilities/migrated.json'
              - 'src-tauri/icons/*.icns'
              - 'src-tauri/icons/*.ico'
              - 'src-tauri/icons/*.png'
              - 'src-tauri/icons/*.svg'
              - 'src-tauri/tauri.conf.json'
            docker:
              - '.github/docker/**'
              - '.github/workflows/docker-build.yml'
            tauri:
              - '.github/workflows/ci.yml'
              - '.github/workflows/lint.yml'
              - '.github/workflows/typos.yml'
              - '.github/actions/setup-*/**'
              - '.github/pr-labeler.yml'
              - 'models/**'
              - 'public/**'
              - 'shared_constants/**'
              - 'src/**'
              - 'src-tauri/Cargo.toml'
              - 'src-tauri/src/**'
              - 'src-tauri/build.rs'
              - 'index.html'
              - 'index.js'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'typos.toml'
              - 'style.css'
              - '.taurignore'
            tests:
              - '.github/workflows/test.yml'
              - '.config/nextest.toml'
            void:
              - 'xbps-template/**'
              - '.github/workflows/void.yml'
            winget:
              - '.github/workflows/winget.yml'
              - '.github/actions/lateste-release-info/action.yml'

      - name: Output branch name
        id: branch
        run: |
          echo "branch=${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT

  typos:
    name: üìù Check typos
    if: always()
    uses: ./.github/workflows/typos.yml

  aur:
    name: AUR
    needs: changes
    if: needs.changes.outputs.aur == 'true'
    uses: ./.github/workflows/aur.yml

  void:
    name: Void
    needs: changes
    if: needs.changes.outputs.void == 'true'
    uses: ./.github/workflows/void.yml

  winget:
    name: winget
    needs: changes
    if: needs.changes.outputs.winget == 'true'
    uses: ./.github/workflows/winget.yml
    secrets: inherit

  lint:
    needs: changes
    if: needs.changes.outputs.tauri == 'true'
    uses: ./.github/workflows/lint.yml

  tests:
    permissions:
      checks: write # required for action-junit-report annotation
    needs: changes
    if: needs.changes.outputs.tauri == 'true' || needs.changes.outputs.tests == 'true'
    uses: ./.github/workflows/test.yml

  android:
    name: "üì±"
    needs: changes
    if: needs.changes.outputs.tauri == 'true' || needs.changes.outputs.android == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/android.yml
    secrets: inherit
    with:
      branch: ${{ needs.changes.outputs.branch }}

  desktop:
    name: "üñ•Ô∏è"
    needs: changes
    if: needs.changes.outputs.tauri == 'true' || needs.changes.outputs.desktop == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/desktop.yml
    secrets: inherit
    with:
      branch: ${{ needs.changes.outputs.branch }}

  docker:
    name: "üê≥"
    needs: changes
    if: needs.changes.outputs.docker == 'true'
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    uses: ./.github/workflows/docker-build.yml
    with:
      branch: ${{ needs.changes.outputs.branch }}

  always-run:
    # used in branch protection rulesets as the only relevant step needing to pass
    name: CI Status
    runs-on: ubuntu-latest
    needs: [typos, aur, void, winget, lint, tests, android, desktop, docker]
    if: always()
    steps:
      - name: Create JSON summary
        id: summary
        run: |
          echo '${{ toJSON(needs) }}' > needs.json
          cat needs.json | jq

      - name: Aggregate results dynamically
        run: |
          jq -r 'to_entries[] | "\(.key) \(.value.result)"' needs.json | while read job result; do
            echo "$job ‚Üí $result"
            if [[ "$result" == "failure" || "$result" == "cancelled" ]]; then
              echo "‚ùå $job failed or was cancelled"
              exit 1
            fi
          done
          echo "‚úÖ None of the required jobs failed."
