# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "CI"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  # measure against bitrot
  # also rotates docker images monthly, by pushing new docker images
  # the rotation will happen by renovate
  # rotate the images in the middle of the month,
  # to avoid duplicate rotations at the beginning of the month,
  # as the source docker images are also mostly rotated once a month
  schedule:
    - cron: "0 0 15 * *"

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

concurrency:
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  label-pr:
    if: github.event_name == 'pull_request'
    name: "ðŸ·ï¸ Label PR"
    permissions:
      contents: read # Needed to read repository contents
      pull-requests: write # Needed to apply labels
      issues: write # Needed to create non existing labels
    runs-on: ubuntu-slim

    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          configuration-path: .github/labeler.yml

  changes:
    name: "ðŸ” Detect Changes"
    runs-on: ubuntu-slim
    outputs:
      android: ${{ steps.filter.outputs.android }}
      aur: ${{ steps.filter.outputs.aur }}
      branch: ${{ steps.branch.outputs.branch }}
      desktop: ${{ steps.filter.outputs.desktop }}
      docker: ${{ steps.filter.outputs.docker }}
      lint: ${{ steps.filter.outputs.lint }}
      tauri: ${{ steps.filter.outputs.tauri }}
      tests: ${{ steps.filter.outputs.tests }}
      void: ${{ steps.filter.outputs.void }}
      winget: ${{ steps.filter.outputs.winget }}
    steps:
      - name: ðŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ðŸ” Check for changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            android:
              - '.github/actions/sbom/**'
              - '.github/workflows/android-reusable.yml'
              - 'src-tauri/capabilities/mobile.json'
              - 'src-tauri/icons/android/**'
              - 'src-tauri/tauri.android.conf.json'
            aur:
              - '.github/workflows/aur-reusable.yml'
              - '.github/actions/lateste-release-info/action.yml'
              - 'packaging/aur/**'
            desktop:
              - '.github/actions/sbom/**'
              - '.github/workflows/desktop-reusable.yml'
              - 'src-tauri/capabilities/migrated.json'
              - 'src-tauri/icons/*.icns'
              - 'src-tauri/icons/*.ico'
              - 'src-tauri/icons/*.png'
              - 'src-tauri/icons/*.svg'
              - 'src-tauri/tauri.conf.json'
            docker:
              - '.github/docker/**'
            tauri:
              - '.github/actions/setup-*/**'
              - 'crates/**'
              - 'public/**'
              - 'src/**'
              - 'src-tauri/Cargo.toml'
              - 'src-tauri/src/**'
              - 'src-tauri/build.rs'
              - 'index.html'
              - 'index.js'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'style.css'
              - '.taurignore'
            lint:
              - '.github/workflows/lint-reusable.yml'
            tests:
              - '.github/workflows/test-reusable.yml'
              - '.config/nextest.toml'
            void:
              - '.github/workflows/void-reusable.yml'
              - 'packaging/void/**'
            winget:
              - '.github/workflows/winget-reusable.yml'
              - '.github/actions/lateste-release-info/action.yml'

      - name: Output branch name
        id: branch
        run: |
          echo "branch=${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT

  typos:
    name: ðŸ“ Check typos
    if: always()
    uses: hrzlgnm/actions/.github/workflows/typos-reusable.yml@c6837576f65628a8e7ffb69d0f4aadd2c42338f9 # v1.5.8

  aur:
    name: AUR
    needs: changes
    if: needs.changes.outputs.aur == 'true'
    uses: ./.github/workflows/aur-reusable.yml

  void:
    name: Void
    needs: changes
    if: needs.changes.outputs.void == 'true'
    uses: ./.github/workflows/void-reusable.yml

  winget:
    name: winget
    needs: changes
    if: needs.changes.outputs.winget == 'true'
    uses: ./.github/workflows/winget-reusable.yml
    secrets: inherit

  lint:
    needs: changes
    if: needs.changes.outputs.tauri == 'true' || needs.changes.outputs.lint == 'true'
    uses: ./.github/workflows/lint-reusable.yml

  tests:
    permissions:
      checks: write # required for action-junit-report annotation
    needs: changes
    if: needs.changes.outputs.tauri == 'true' || needs.changes.outputs.tests == 'true'
    uses: ./.github/workflows/test-reusable.yml

  android:
    name: "ðŸ“±"
    needs: changes
    if: needs.changes.outputs.tauri == 'true' || needs.changes.outputs.android == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/android-reusable.yml
    secrets: inherit
    with:
      branch: ${{ needs.changes.outputs.branch }}

  desktop:
    name: "ðŸ–¥ï¸"
    needs: changes
    if: needs.changes.outputs.tauri == 'true' || needs.changes.outputs.desktop == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/desktop-reusable.yml
    secrets: inherit
    with:
      branch: ${{ needs.changes.outputs.branch }}

  docker:
    name: "ðŸ³"
    needs: changes
    if: needs.changes.outputs.docker == 'true'
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    uses: hrzlgnm/actions/.github/workflows/docker-reusable.yml@c6837576f65628a8e7ffb69d0f4aadd2c42338f9 # v1.5.8
    with:
      branch: ${{ needs.changes.outputs.branch }}

  all-required-green: # This job does nothing and is only used for the branch protection
    name: CI Status
    runs-on: ubuntu-latest
    needs:
      - typos
      - aur
      - void
      - winget
      - lint
      - tests
      - android
      - desktop
      - docker
    if: always()
    steps:
      - name: Check whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@2765efec08f0fd63e83ad900f5fd75646be69ff6
        with:
          allowed-skips: >-
            aur,
            void,
            winget,
            lint,
            tests,
            android,
            desktop,
            docker
          jobs: ${{ toJSON(needs) }}
