name: Build Changed Dockerfiles

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: The branch name we are building, eg 'main'
        required: true
  workflow_dispatch:

jobs:
  changed-dockerfiles:
    name: ğŸ” Dockerfiles
    runs-on: ubuntu-slim
    outputs:
      packages: ${{ steps.packages.outputs.packages }}
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: ğŸ” Filter changed Dockerfiles
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          list-files: json
          filters: |
            dockerfiles:
              - '.github/docker/*/Dockerfile'

      - name: ğŸ§© Extract package names
        id: packages
        run: |
          paths='${{ steps.filter.outputs.dockerfiles_files }}'

          names=$(echo "$paths" \
            | jq -r '.[]' \
            | while read path; do
                # Only keep if the Dockerfile exists, so removed ones are not built
                if [ -f "$path" ]; then
                  echo "$path" | awk -F'/' '{print $3}'
                fi
              done \
            | jq -R -s -c 'split("\n")[:-1]')

          echo "packages=$names" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: changed-dockerfiles
    if: ${{ needs.changed-dockerfiles.outputs.packages != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.changed-dockerfiles.outputs.packages) }}

    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: ğŸ” Login to GHCR (main only)
        if: inputs.branch == 'main'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ”§ Build image (and ğŸš€ push on main)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .github/docker/${{ matrix.package }}
          file: .github/docker/${{ matrix.package }}/Dockerfile

          push: ${{ inputs.branch == 'main' }}

          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.package }}:v1
            ghcr.io/${{ github.repository_owner }}/${{ matrix.package }}:latest
