name: "Reusable ci lint workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: ğŸ§ğŸ“
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/mdns-browser-ubuntu-builder:v1@sha256:86a96fed7be109a25b056afae0958d7925b3da4d4a9f58c224abe130bccceade

    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: ğŸ¦€ğŸš€
        uses: ./.github/actions/setup-rust-cache
        with:
          components: rustfmt

      - name: ğŸ“ Run rustfmt and fail if any warnings
        shell: bash
        run: |
          cargo fmt -- --check
          cd src-tauri
          cargo fmt -- --check

      - name: ğŸ“¥ Cached install leptosfmt
        uses: baptiste0928/cargo-install@b687c656bda5733207e629b50a22bf68974a0305 # v3
        with:
          crate: leptosfmt
          version: 0.1.33
          locked: true

      - name: ğŸ“ Run leptosfmt and fail if any warnings
        run: |
          leptosfmt --check src

  clippy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
            symbol: ğŸ§
            platform: Linux
            container_image: ghcr.io/hrzlgnm/mdns-browser-ubuntu-builder:v1@sha256:86a96fed7be109a25b056afae0958d7925b3da4d4a9f58c224abe130bccceade
          - os: "macos-latest"
            symbol: ğŸ
          - os: "windows-latest"
            symbol: ğŸªŸ
    runs-on: ${{matrix.os}}
    name: ${{matrix.symbol}}ğŸ“
    container: ${{ contains(matrix.os, 'ubuntu') && matrix.container_image || null }}
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: ğŸ¦€ğŸš€
        uses: ./.github/actions/setup-rust-cache
        with:
          components: clippy
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin,wasm32-unknown-unknown' || 'wasm32-unknown-unknown' }}

      - name: ğŸ› ï¸ğŸš€
        uses: ./.github/actions/setup-sccache

      - name: ğŸ“ Run clippy and fail if any warnings
        shell: bash
        run: |
          cargo clippy -- -D warnings
          cd src-tauri
          cargo clippy -- -D warnings
