name: "Publish release artifacts"

on:
  release:
    types:
      - published

jobs:
  source-checksum:
    permissions:
      contents: write
      actions: read
    uses: ./.github/workflows/source-checksum.yml
    secrets: inherit

  android:
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
    uses: ./.github/workflows/android.yml
    secrets: inherit
    with:
      tagName: ${{ github.event.release.tag_name }}

  desktop:
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
    uses: ./.github/workflows/desktop.yml
    secrets: inherit
    with:
      tagName: ${{ github.event.release.tag_name }}

  void:
    needs:
      - source-checksum
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
    uses: ./.github/workflows/void.yml
    secrets: inherit
    with:
      tagName: ${{ github.event.release.tag_name }}

  checksums:
    needs:
      - android
      - desktop
      - void
    permissions:
      contents: write
      actions: read
    uses: ./.github/workflows/release-checksums.yml
    secrets: inherit
    with:
      tagName: ${{ github.event.release.tag_name }}
