name: Publish release artifacts

on:
  release:
    types:
      - published

jobs:
  source:
    permissions:
      contents: write
      actions: read
    uses: ./.github/workflows/source-checksums.yml
    secrets: inherit

  android:
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
    uses: ./.github/workflows/android.yml
    secrets: inherit
    with:
      tagName: ${{ github.event.release.tag_name }}

  desktop:
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
    uses: ./.github/workflows/desktop.yml
    secrets: inherit
    with:
      tagName: ${{ github.event.release.tag_name }}

  void:
    needs:
      - source
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
    uses: ./.github/workflows/void.yml
    secrets: inherit
    with:
      tagName: ${{ github.event.release.tag_name }}

  asset:
    needs:
      - android
      - desktop
      - void
    permissions:
      contents: write
      actions: read
    uses: ./.github/workflows/asset-checksums.yml
    secrets: inherit
