name: Create and publish checksums
on:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver of the release to publish for
        type: string
        required: true
  release:
    types: [released]

permissions:
  contents: write

jobs:
  release_info:
    name: Get release info
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.release_info.outputs.tag-name }}
    steps:
      - name: determine release info
        id: release_info
        run: |
          if [ -n "${{ github.event.release.name }}" ]; then
            echo "tag-name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag-name=mdns-browser-v${{ github.event.inputs.semver }}" >> $GITHUB_OUTPUT
          fi

  generate_checksums:
    name: Generate checksums
    runs-on: ubuntu-latest
    needs:
      - release_info
    strategy:
      matrix:
        algorithm: [sha256]
    steps:
      - name: download assets
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          repository: hrzlgnm/mdns-browser
          tag: ${{ needs.release_info.outputs.tag-name }}
          fileName: "mdns?browser*"
      - name: Download tarball and generate checksum files
        run: |
          set -o errexit
          curl -sLO https://github.com/hrzlgnm/mdns-browser/archive/refs/tags/${{ needs.release_info.outputs.tag-name }}.tar.gz
          for file in *; do
            if [ -f "$file" ] && [[ "$file" != *.sha* ]]; then
              ${{ matrix.algorithm }}sum "$file" > "$file.${{ matrix.algorithm }}"
            fi
          done
      - name: Upload checksum files
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: ${{ matrix.algorithm }}-checksums
          path: "*.${{ matrix.algorithm }}"

  publish:
    name: Publish checksum assets
    runs-on: ubuntu-latest
    needs:
      - release_info
      - generate_checksums
    steps:
      - name: Download all produced artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6

      - name: publish checksum assets
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.release_info.outputs.tag-name }}
          append_body: true
          make_latest: false
          generate_release_notes: false
          files: |
            **/*.sha*
