name: Create and publish checksums
on:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver of the release to publish for
        type: string
        required: true
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release_info:
    name: Get release info
    runs-on: ubuntu-24.04
    outputs:
      tag-name: ${{ steps.release_info.outputs.tag-name }}
    steps:
      - name: determine release info
        id: release_info
        run: |
          if [ -n "${{ github.event.release.name }}" ]; then
            echo "tag-name=${{ github.event.release.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag-name=mdns-browser-v${{ github.event.inputs.semver }}" >> $GITHUB_OUTPUT
          fi

  sha256:
    name: Generate sha256 checksums
    runs-on: ubuntu-24.04
    needs:
      - release_info
    outputs:
      file: sha256sums.txt
    steps:
      - uses: robinraju/release-downloader@v1.12
        with:
          repository: hrzlgnm/mdns-browser
          tag: ${{ needs.release_info.outputs.tag-name }}
          fileName: "*"
          tarBall: true
          zipBall: true
      - name: sha256
        run: sha256sum * > sha256sums.txt
      - name: upload sha256 checksum
        uses: actions/upload-artifact@v4
        with:
          name: sha256sums
          path: sha256sums.txt

  sha512:
    name: Generate sha512 checksums
    runs-on: ubuntu-24.04
    needs:
      - release_info
    outputs:
      file: sha512sums.txt
    steps:
      - uses: robinraju/release-downloader@v1.12
        with:
          repository: hrzlgnm/mdns-browser
          tag: ${{ needs.release_info.outputs.tag-name }}
          fileName: "*"
          tarBall: true
          zipBall: true
      - name: sha512
        run: sha512sum * > sha512sums.txt
      - name: upload sha512 checksum
        uses: actions/upload-artifact@v4
        with:
          name: sha512sums
          path: sha512sums.txt

  publish:
    name: Publish checksum assets
    runs-on: ubuntu-24.04
    needs:
      - release_info
      - sha256
      - sha512
    steps:
      - name: Download all produced artifacts
        uses: actions/download-artifact@v4

      - name: ls
        run: ls -R

      - name: publish checksum assets
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.release_info.outputs.tag-name }}
          append_body: true
          make_latest: false
          generate_release_notes: false
          files: |
            sha256sums.txt
            sha512sums.txt
