# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: Create and publish source checksum
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver of the release to publish for
        type: string
        required: true

permissions:
  contents: write

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-slim
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: ğŸ·ï¸
        id: tag
        run: |
          if [ -n "${{ github.event.release.name }}" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=mdns-browser-v${{ github.event.inputs.semver }}" >> $GITHUB_OUTPUT
          fi

  generate_checksums:
    name: ğŸ”¢â˜‘ï¸
    runs-on: ubuntu-slim
    needs:
      - tag
    strategy:
      matrix:
        algorithm: [sha256]
    steps:
      - name: ğŸ“¥ğŸ”¢â˜‘ï¸
        run: |
          set -o errexit
          curl -sLO https://github.com/hrzlgnm/mdns-browser/archive/refs/tags/${{ needs.tag.outputs.tag }}.tar.gz
          curl -sLO https://github.com/hrzlgnm/mdns-browser/archive/refs/tags/${{ needs.tag.outputs.tag }}.zip
          for file in *; do
            if [ -f "$file" ] && [[ "$file" != *.sha* ]]; then
              ${{ matrix.algorithm }}sum "$file" > "$file.${{ matrix.algorithm }}"
            fi
          done
      - name: ğŸ“¤
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: ${{ matrix.algorithm }}-source-checksums
          path: "*.${{ matrix.algorithm }}"

  publish:
    name: ğŸ“°ğŸ”¢â˜‘ï¸
    runs-on: ubuntu-slim
    needs:
      - tag
      - generate_checksums
    steps:
      - name: ğŸ“¥ artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7

      - name: ğŸ“°ğŸ”¢â˜‘ï¸
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          append_body: true
          make_latest: false
          generate_release_notes: false
          files: |
            **/*.sha*
